Controllers/HomeController.cs
using System.Web.Mvc;

namespace CVSUpload.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cvs()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Excel()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

Controllers/ImportCSVController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using CVSUpload.Models;
using MailBee.Mime;

namespace CVSUpload.Controllers
{
    public class ImportCSVController : Controller
    {
        // GET: Import
        public ActionResult Index()
        {
            return View();
        }
 
        /// <summary>
        /// Post method for importing users 
        /// </summary>
        /// <param name="postedFile"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                try
                {
                    string fileExtension = Path.GetExtension(postedFile.FileName);
 
                    //Validate uploaded file and return error.
                    if (fileExtension != ".csv")
                    {
                        ViewBag.Message = "Please select the csv file with .csv extension";
                        return View();
                    }
 
 
                    var students = new List<StudentCSV>();
                    using (var sreader = new StreamReader(postedFile.InputStream))
                    {
                        //First line is header. If header is not passed in csv then we can neglect the below line.
                        string[] headers = sreader.ReadLine().Split(';',',');
                        //Loop through the records
                        while (!sreader.EndOfStream)
                        {
                            string[] rows = sreader.ReadLine().Split(';',',');
 
                            students.Add(new StudentCSV
                            {
                                EmployeeId = int.Parse(rows[0].ToString()),
                                EmployeeName = rows[1].ToString(),
                                Designation = rows[2].ToString(),
                                Salary = int.Parse(rows[3].ToString()),
                                Email = EmailAddress.Parse(rows[4].ToString())
                            });
                        }
                    }
 
                    return View("View", students);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;
                }
            }
            else
            {
                ViewBag.Message = "Please select the file first to upload.";
            }
            return View();
        }
    }
}

Controllers/ImportXLSXController.cs
using CVSUpload.Models;
using System;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Web;
using System.Web.Mvc;

using MailBee.Mime;

using System.Collections.Generic;


using DataTable = System.Data.DataTable;

namespace CVSUpload.Controllers
{
    public class ImportXLSXController : Controller
    {
        // GET: Import
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Post method for importing users 
        /// </summary>
        /// <param name="postedFile"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                try
                {
                    string fileExtension = Path.GetExtension(postedFile.FileName);

                    //Validate uploaded file and return error.
                    if(fileExtension != ".xls" && fileExtension != ".xlsx" && fileExtension != ".csv")
                    {
                        ViewBag.Message = "Please select the excel file with .xls or .xlsx extension";
                        return View();
                    }

                    string folderPath = Server.MapPath("~/UploadedFiles/");
                    //Check Directory exists else create one
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }

                    //Save file to folder
                    var filePath = folderPath + Path.GetFileName(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    //Get file extension
                   
                    string excelConString = "";

                    //Get connection string using extension 
                    switch (fileExtension)
                    {
                        //If uploaded file is Excel 1997-2007.
                        case ".xls":
                            excelConString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0};Extended Properties='Excel 8.0;HDR=YES'";
                            break;
                        //If uploaded file is Excel 2007 and above
                        case ".xlsx":
                            excelConString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties='Excel 8.0;HDR=YES'";
                            break;
                        //upload file
                        case ".csv":
                            excelConString = "Driver={Microsoft Text Driver (*.txt; *.csv)};Dbq=;Extensions=asc,csv,tab,txt;Persist Security Info=False";
                            break;
                            
                    }

                    //Read data from first sheet of excel into datatable
                    DataTable dt = new DataTable();
                    excelConString = string.Format(excelConString, filePath);

                    using (OleDbConnection excelOledbConnection = new OleDbConnection(excelConString))
                    {
                        using (OleDbCommand excelDbCommand = new OleDbCommand())
                        {
                            using (OleDbDataAdapter excelDataAdapter = new OleDbDataAdapter())
                            {
                                excelDbCommand.Connection = excelOledbConnection;

                                excelOledbConnection.Open();
                                //Get schema from excel sheet
                                DataTable excelSchema = GetSchemaFromExcel(excelOledbConnection);
                                //Get sheet name
                                string sheetName = excelSchema.Rows[0]["TABLE_NAME"].ToString();
                                excelOledbConnection.Close();

                                //Read Data from First Sheet.
                                excelOledbConnection.Open();
                                excelDbCommand.CommandText = "SELECT * From [" + sheetName + "]";
                                excelDataAdapter.SelectCommand = excelDbCommand;
                                //Fill datatable from adapter
                                excelDataAdapter.Fill(dt);
                                excelOledbConnection.Close();
                            }
                            
                        }
                    }

                    var students = new List<StudentXLSX>();
                    //Insert records to Student table.
                    using (var context = new UploadContext())
                    {
                        //Loop through datatable and add student data to student table. 
                        foreach (DataRow row in dt.Rows)
                        {
                            students.Add(GetStudentFromExcelRow(row));
                        }
                    }
                    return View("View",students);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;
                }
            }
            else
            {
                ViewBag.Message = "Please select the file first to upload.";
            }
            return View();
        }

        private static DataTable GetSchemaFromExcel(OleDbConnection excelOledbConnection)
        {
            return excelOledbConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
        }

        //Convert each datarow into student object
        private StudentXLSX GetStudentFromExcelRow(DataRow row )
        {
            return new StudentXLSX
            {
                EmployeeId = int.Parse(row[0].ToString()),
                EmployeeName = row[1].ToString(),
                Designation = row[2].ToString(),
                Salary = int.Parse(row[3].ToString()),
                Email = EmailAddress.Parse(row[4].ToString()),
            };
        }
    }
}

Views/Home/Cvs.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

 
<div class="container">
      <div class="tab-content">
        <div class="tab-pane active">
            <div class="row">
                @using (Html.BeginForm("Index", "ImportCSV", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-group">
 
                        @Html.Label("File Upload", new { @class = "col-sm-3" })
 
                        <div class="col-sm-7">
                            <input type="file" id="postedFile" name="postedFile" class="form-control" accept=".csv" />
                        </div>
                    </div>
 
                    <div class="form-group">
 
                        <div class="col-md-offset-3 col-md-10">
                            <br />
                            <input type="submit" title="Upload" value="Upload" class="btn btn-default" />
                        </div>
                    </div>
                    <div class="form-group">
 
                        <div class="col-md-offset-3 col-md-10">
                            <br />
                            <span style="color:red;">
                                @ViewBag.Message
                            </span>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Home/Excel.cshtml
@{
    ViewBag.Title = "Index";
}
 
<h2>Upload and read Excel file in ASP.Net MVC</h2>
 
<div class="container">
    <div class="tab-content">
        <div class="tab-pane active">
            <div class="row">
                @using (Html.BeginForm("Index", "ImportXLSX", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-group">
 
                        @Html.Label("File Upload", new { @class = "col-sm-3" })
 
                        <div class="col-sm-7">
                            <input type="file" id="postedFile" name="postedFile" class="form-control" accept=" .xlsx, .xls" />
                        </div>
                    </div>
 
                    <div class="form-group">
 
                        <div class="col-md-offset-3 col-md-10">
                            <br />
                            <input type="submit" title="Upload" value="Upload" class="btn btn-default" />
                        </div>
                    </div>
                    <div class="form-group">
 
                        <div class="col-md-offset-3 col-md-10">
                            <br />
                            <span style="color:red;">
                                @ViewBag.Message
                            </span>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
 
<h1>HOME</h1>